sudo: false
language: ruby

before_install:
  # https://github.com/bundler/bundler/issues/3558
  gem update bundler

script: env COVERAGE=yes bundle exec rake

matrix:
  fast_finish: true
  include:
  - rvm: '2.4'
    env: PUPPET_GEM_VERSION='~> 5.0'
  - rvm: '2.3'
    env: PUPPET_GEM_VERSION='~> 5.0'
  - rvm: '2.1'
    env: PUPPET_GEM_VERSION='~> 5.0'

notifications:
email: false
